//
// Generated file, do not edit! Created by nedtool 5.5 from arrivalRateMsg.msg.
//

#ifndef __ARRIVALRATEMSG_M_H
#define __ARRIVALRATEMSG_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0505
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>arrivalRateMsg.msg:19</tt> by nedtool.
 * <pre>
 * //
 * // TODO generated message class
 * //
 * message arrivalRateMsg
 * {
 *     bool ask;
 *     int sourceID;
 *     double lambda;
 *     double mu;
 * }
 * </pre>
 */
class arrivalRateMsg : public ::omnetpp::cMessage
{
  protected:
    bool ask;
    int sourceID;
    double lambda;
    double mu;

  private:
    void copy(const arrivalRateMsg& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const arrivalRateMsg&);

  public:
    arrivalRateMsg(const char *name=nullptr, short kind=0);
    arrivalRateMsg(const arrivalRateMsg& other);
    virtual ~arrivalRateMsg();
    arrivalRateMsg& operator=(const arrivalRateMsg& other);
    virtual arrivalRateMsg *dup() const override {return new arrivalRateMsg(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual bool getAsk() const;
    virtual void setAsk(bool ask);
    virtual int getSourceID() const;
    virtual void setSourceID(int sourceID);
    virtual double getLambda() const;
    virtual void setLambda(double lambda);
    virtual double getMu() const;
    virtual void setMu(double mu);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const arrivalRateMsg& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, arrivalRateMsg& obj) {obj.parsimUnpack(b);}


#endif // ifndef __ARRIVALRATEMSG_M_H

